language:  node_js
node_js:
  - "4.2"
addons:
  code_climate:
    repo_token: 20a2c25e4d6dadb3098da02f8f512613d4e8db04a0fa6405810bde0ce8dbdf89
script:
  - npm test
after_success:
  - npm run cover
  - npm run report
  # - codeclimate-test-reporter < ./coverage/lcov.info
