language:  node_js
node_js:
  - "4.2"
addons:
  code_climate:
    repo_token: 20a2c25e4d6dadb3098da02f8f512613d4e8db04a0fa6405810bde0ce8dbdf89

after_scripts:
  - codeclimate-test-reporter < lcov.info

env:
  - CODECLIMATE_REPO_TOKEN=20a2c25e4d6dadb3098da02f8f512613d4e8db04a0fa6405810bde0ce8dbdf89 codeclimate-test-reporter < lcov.info